### ISSUE TITLE
 pyfeltor's use of nlohmann::json cannot be seen as the struct  dg::file::WrappedJsonValue ( json::value )used  in feltor ,causing compile errors

### ISSUE THREAD

**Issue by syzeng** [feltor-dev/pyFeltor#2]
Hi!
Your pyfeltor project use the nlohmann/json parser.In `pyfeltor/dg/geo/solovev.cpp` (and other cpp files in the same directory),you use 

```c++
#include "dg/geometries/geometries.h"
namespace py = pybind11;
namespace poly = dg::geo::solovev;
PYBIND11_MODULE(solovev, m) { // name of the python module, not the C++ file
    py::class_<poly::Parameters>(m,"Parameters")
		.def(py::init( [](const nlohmann::json& js){
                    return std::make_unique<poly::Parameters>(js);}))
```

since `namespace poly = dg::geo::solovev;`,in your feltor project ,namespace `dg::geo::solovev` contains struct `Parameters`,it is constructed from Json dataset:

```
	Parameters (const dg::file::WrappedJsonValue &js)
```

namespace `dg::file` contains struct `WrappedJsonValue`.You say in your doxygen document:'You can use the `WrappedJsonValue` like a `Json::Value` with read-only access:'So I suppose `struct dg::file::WrappedJsonValue` and `Json::Value` have the same datatype.So the `dg::geo::solovev::Parameters` can only accepts struct `dg::file::WrappedJsonValue` or `Json::Value`.

But `Json::Value` is not equal to `nlohmann::json` .So when I compiled pyfeltor,I meet compile error in `pyfeltor/dg/geo/solovev.cpp`,and error message is put below .It means,when calling the constructor of the dg::geo::solovev::Parameters class, a version that accepts a const nlohmann::basic_json<>& parameter cannot be found.

```
/usr/include/c++/11/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = dg::geo::solovev::Parameters; _Args = {const nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<dg::geo::solovev::Parameters, std::default_delete<dg::geo::solovev::Parameters> >]’:
pyfeltor/dg/geo/solovev.cpp:15:62:   required from here
/usr/include/c++/11/bits/unique_ptr.h:962:30: error: no matching function for call to ‘dg::geo::solovev::Parameters::Parameters(const nlohmann::basic_json<>&)’
  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
```

A possible way to solve the problem is to use `Json::Value` (jsoncpp) instead of  `nlohmann::json` ( nlohmann/json) .In pyfeltor,you use `nlohmann::json` in many files.I wonder why you can compile passed using `nlohmann::json` ,and whether you have solved the problem.Thank you!

Reference:

[[Extension: Geometries: dg::geo::solovev::Parameters Struct Reference (mwiesenberger.github.io)](https://mwiesenberger.github.io/feltor/geometries/html/structdg_1_1geo_1_1solovev_1_1_parameters.html)](https://mwiesenberger.github.io/feltor/geometries/html/structdg_1_1geo_1_1solovev_1_1_parameters.html)

[[Extension: Json and NetCDF utilities: dg::file::WrappedJsonValue Struct Reference (mwiesenberger.github.io)](https://mwiesenberger.github.io/feltor/file/html/structdg_1_1file_1_1_wrapped_json_value.html)](https://mwiesenberger.github.io/feltor/file/html/structdg_1_1file_1_1_wrapped_json_value.html)

**Comment by mwiesenberger** [comment]
Hi,
thanks for pointing this out.
 yes I use nlohmann::json because it already comes with a pybind11 binding module so it is possible and easy to use directly in python. jsoncpp unfortunately does not have these bindings so would require additional work (or some imo ugly workarounds) to bind in python. Additionally, nlohmann json is header only and thus easier to include in a C++ project than jsoncpp which requires compilation and linking. 

Thus, I created a new feature in feltor (C++) to use nlohmann json instead of jsoncpp using the macro DG_USE_JSONHPP. Currently, it is only available on the develop branch so the solution would be to go to the feltor repository and do `git checkout develop` and recompile pyfeltor

I plan to merge the develop branch into the master branch as v7.1 in the near future and update this requirement in pyfeltor

Hope this helps
Matthias

**Comment by syzeng** [comment]
It seems the develop branch of feltor is not visible to me since I can't see any other branches of feltor.Could you set it visible to me?I'll appreciate it.

**Comment by mwiesenberger** [comment]
Ah, sorry I forgot to mention, it is mwiesenberger/feltor that has my develop branch not feltor-dev/feltor
So you need to add `git remote add mwiesenberger https://github.com/mwiesenberger/feltor`  then `git fetch mwiesenberger` and then checkout to develop
